### ISSUE TITLE
ESRAP::TEXT/BOUNDS no longer exists

### ISSUE THREAD

**Issue by quicklisp** [fb08af68/esrap-peg#1]
The latest esrap no longer includes text/bounds. Per IRC, the author says:

```
14:47 <scymtym> Xach_: esrap-peg is using a formerly internal symbol that no 
      longer exists. assuming esrap-peg is maintained, it can easily be 
      fixed by adding the (three-line) function that has been removed from 
      esrap
```

**Comment by fb08af68** [comment]
I think I have noticed it a month later and indeed more or less copied the function. Thanks for copying the advice here, not sure at which points Github email notification worked and did not work for me.
